package Clases;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ORTIZ
 */
public class Estadisticas extends javax.swing.JFrame {
    private String Cadena; 
    private int suma;
     private int indice=0;
     private double Promedio;
    Estadistica S=new Estadistica();
    ArrayList lista=new ArrayList();
        ArrayList lista1=new ArrayList();

    public Estadisticas() {
        
      super("Estadistica   ");
       
        initComponents();
           this.setLocationRelativeTo(null); 

    }
   
  public   int  getSum(int numero){
      indice++;
        suma=suma+numero;
   return this.suma; }
//promedio
    public   double  getAverage() {
        Promedio=suma/indice;
   return this.Promedio; }  

  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBminimizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ingresoTx = new javax.swing.JTextField();
        jBenter = new javax.swing.JButton();
        jBclear = new javax.swing.JButton();
        jLnumeroentrada = new javax.swing.JLabel();
        jLSuma = new javax.swing.JLabel();
        jTEntrada = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTSum = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Ingrese un numero y presione Enter :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 50));

        ingresoTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoTxActionPerformed(evt);
            }
        });
        ingresoTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresoTxKeyTyped(evt);
            }
        });
        jPanel1.add(ingresoTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 40));

        jBenter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBenter.setText("Enter");
        jBenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBenterActionPerformed(evt);
            }
        });
        jPanel1.add(jBenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 90, 40));

        jBclear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBclear.setText("Clear");
        jBclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBclearActionPerformed(evt);
            }
        });
        jPanel1.add(jBclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 90, 40));

        jLnumeroentrada.setText("Numeros de Entradas : ");
        jPanel1.add(jLnumeroentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 30));

        jLSuma.setText("Suma :");
        jPanel1.add(jLSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jTEntrada.setText(" ");
        jPanel1.add(jTEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 120, 20));

        jButton1.setText("Promedio ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 224, 130, 20));

        jTSum.setText(" ");
        jPanel1.add(jTSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 174, 140, 30));

        jMenu1.setText("Clear");

        jMenuItem1.setText("Mostar Clear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoTxActionPerformed
      
    }//GEN-LAST:event_ingresoTxActionPerformed

    private void jBenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBenterActionPerformed
    int numero=Integer.parseInt(ingresoTx.getText());
        lista.add(ingresoTx.getText());
        S.getCount();
        jTEntrada.setText(S.getContador()+"");
      ingresoTx.setText(null);
        jTSum.setText(getSum(numero)+"");
       jLabel2.setText(null);
        
    }//GEN-LAST:event_jBenterActionPerformed

    private void ingresoTxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresoTxKeyTyped

        // JTextField a=new JTextField(jTextField1);
        int k = (int) evt.getKeyChar();
//este if no permite el ingreso de letras y otros simoboloes
        if (k >= 46 && k <= 57) {

            if (k == 46) {
                String dato = ingresoTx.getText();
                int tama = dato.length();
                for (int i = 0; i <= tama; i++) {
                    if (dato.contains("")) {
                        evt.setKeyChar((char) KeyEvent.VK_CLEAR);

                    }
                }
            }
        } else {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoTxKeyTyped

    private void jBclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBclearActionPerformed
lista1.add(ingresoTx.getText());
      ingresoTx.setText(null);

                // TODO add your handling code here:
    }//GEN-LAST:event_jBclearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jLabel2.setText( getAverage()+"");       

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
dispose();        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        for (int i = 0; i < lista1.size(); i++) {
            Cadena+="["+i+"]:"+lista1.get(i)+"  \n";
        }
        JOptionPane.showMessageDialog(this,"Datos\n"+ Cadena);
        Cadena="";
     // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ingresoTx;
    private javax.swing.JButton jBclear;
    private javax.swing.JButton jBenter;
    private javax.swing.JButton jBminimizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLnumeroentrada;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTEntrada;
    private javax.swing.JLabel jTSum;
    // End of variables declaration//GEN-END:variables
}
