/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package numaletra;

import javax.swing.JOptionPane;

/**
 *
 * @author Alisz
 */
public class fran extends javax.swing.JFrame {
    public final String [] unidad= {"","uno","dos","tres","cuatro","cinco","seis","siete","ocho","nueve"}; 
    public final String [] di= {"","Once","Doce","Trece","Catorce","Quince", "Dieciseis", "Dieciete","Dieciocho","Diecinueve"};
    public final String [] decenas= {"","Diez","Veinti","Treinta","Cuarenta", "Cincuenta", "Sesenta", "Setenta", "Ochenta","Noventa"};
    public final String [] centenas = {"","Ciento","Doscientos","Trecientos","Cuatrociento","Quinientos","Seiscientos","Setecientos","Ochocientos","Novecientos"};

    int numero, u, d, m,dd;
   
    public fran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Letra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
 
        String num= jTextField1.getText();
        int nn= Integer.parseInt(num);
        nn=nn/10;
        dd=nn%10;
       
       
       numero=Integer.parseInt(jTextField1.getText());
        m= numero/100;
        d=numero/10;
    //    numero=numero/10;
   //     dd =numero%10;
        u= numero%10;
       
      // dd=numero/1;
      
        String i=   jTextField1.getText();
         
             int j= Integer.valueOf(i); 
     
        if(j<10){
         
           for (int e=0;e<unidad.length;e++){
               if (u==e){
                   
                   jLabel1.setText(unidad[e]);
               }
           }
        }else {
            if(j<20){
                if(u==0){
                    jLabel1.setText("Diez");
                }else{
                   for(int ee=0; ee<di.length;ee++){
                    
                         if(u==ee){
                             jLabel1.setText(di[ee]);
                         }
                     
                        
                        }  
                }
                 
                
                
            }else{
                if(j<100){
              if(j==20){
                  jLabel1.setText("Veinte");
              }else{
               
                    if(u==0){
                    
                    for(int ee=0; ee<decenas.length;ee++){
                        
                            if(d==ee){
                               
                            jLabel1.setText(decenas[ee]);
                        
                        }
                       
                    
                    }  
                    }else{if(j<30){
                         System.out.print("Entro"+d+""+u);
                         for(int ee=0; ee<decenas.length;ee++){
                             for(int p=0; p<unidad.length;p++){
                                     if(d==ee){
                                         if(u==p){
                                              jLabel1.setText(decenas[ee]+unidad[p]);
                                         }
                               
                           
                        
                        }
                                 
                             }
                         }
                    }else{
                          for(int ee=0; ee<decenas.length;ee++){
                             for(int p=0; p<unidad.length;p++){
                                     if(d==ee){
                                         if(u==p){
                                              jLabel1.setText(decenas[ee]+" y "+unidad[p]);
                                         }
                               
                           
                        
                        }
                                 
                             }
                         }
                        
                    }
                    }
                        
                    }
                  
                }else{
                    if(j<1000){
                        System.out.print(u);
                        if(dd==2){
                            if(u==0){
                                for(int ee=0; ee<centenas.length;ee++){
                                if(m==ee){
                                    jLabel1.setText(centenas[ee]+" Veinte");
                                }
                            } 
                            }
                           
                            
                        }else{
                            
                        
                        if(j==100){
                            jLabel1.setText("Cien");
                        }else{
                             if(j==110){
                                    jLabel1.setText("Ciento Diez");
                                }
                        else{
                       
                            if( dd==1){
                               
                                    
                               for(int ee=0; ee<centenas.length;ee++){
                                   for(int s=0; s<di.length;s++){
                    
                         if(m==ee){
                             if(u==s){
                                 jLabel1.setText(centenas[ee]+" "+di[s]);
                             }
                             
                         }
                     
                        
                        }  
                            
                               } 
                                
                            }else{
                     if(dd==2){
                          for(int ee=0; ee<centenas.length;ee++){
                             for(int p=0; p<decenas.length;p++){
                                 for(int f=0; f<unidad.length;f++){
                                     if(m==ee){
                                         if(dd==p){
                                             if(u==f){
                                                 jLabel1.setText(centenas[ee]+" "+decenas[p]+unidad[f]);
                                             }
                                               
                                         }
                                      
                                     }
                                     
                                 }
                                 }
                       
                                 
                             }
                     }else{
                         if(u==0){
                            for(int ee=0; ee<centenas.length;ee++){
                             for(int p=0; p<decenas.length;p++){
                                 for(int f=0; f<unidad.length;f++){
                                     if(m==ee){
                                         if(dd==p){
                                             if(u==f){
                                                 jLabel1.setText(centenas[ee]+" "+decenas[p]);
                                             }
                                               
                                         }
                                      
                                     }
                                     
                                 }
                                 }
                       
                                 
                             } 
                         }else{
                                for(int ee=0; ee<centenas.length;ee++){
                             for(int p=0; p<decenas.length;p++){
                                 for(int f=0; f<unidad.length;f++){
                                     if(m==ee){
                                         if(dd==p){
                                             if(u==f){
                                                 jLabel1.setText(centenas[ee]+" "+decenas[p]+" y "+unidad[f]);
                                             }
                                               
                                         }
                                      
                                     }
                                     
                                 }
                                 }
                       
                                 
                             } 
                             
                         }
                         
                     }
                     }
                             
                         }
                            }
                        }
                        
                    }
                }
            }
          
        }
    

        
    }//GEN-LAST:event_jButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new fran().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the unidad
     */
    public String[] getUnidad() {
        return unidad;
    }

    /**
     * @param unidad the unidad to set
     */
  
}
