/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IGU;

import Clases_SubClases.Circulo;
import Clases_SubClases.DatosCuadrado;
import Clases_SubClases.DatosCubo;
import Clases_SubClases.Esfera;
import Clases_SubClases.Piramide;
import Clases_SubClases.Triangulo;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author GOYO
 */
public class Cuadrado extends javax.swing.JFrame {
DatosCuadrado cua;
Piramide Pira;
Triangulo tri;
Esfera es;
Circulo circ;
DatosCubo Cub;
     /**
     * Creates new form Cuadrado
     */
    public Cuadrado() {
       
         super("Figura 2D y 3D\n  ");	
   

      Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
      int height = pantalla.height;
      int width = pantalla.width;
      setSize(width/2, height/2);		
 
      setLocationRelativeTo(null);		
      setVisible(true);
         initComponents();
    }
    public void Paint(Graphics2D d){
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        Triangulo = new javax.swing.JMenuItem();
        circulo = new javax.swing.JMenuItem();
        Cuadrado = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        cubo = new javax.swing.JMenuItem();
        Esfera = new javax.swing.JMenuItem();
        Piramide = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagesa.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jButton1.setText("jButton1");

        jMenu3.setText("Figuras");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu5.setText("Figura 2D");
        jMenu5.setMaximumSize(new java.awt.Dimension(327676, 327676));
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        Triangulo.setText("Triangulo");
        Triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrianguloActionPerformed(evt);
            }
        });
        jMenu5.add(Triangulo);

        circulo.setText("Circulo");
        circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circuloActionPerformed(evt);
            }
        });
        jMenu5.add(circulo);

        Cuadrado.setText("Cuadrado");
        Cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadradoActionPerformed(evt);
            }
        });
        jMenu5.add(Cuadrado);

        jMenu3.add(jMenu5);

        jMenu6.setText("Figura 3D");

        cubo.setText("Cubo");
        cubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuboActionPerformed(evt);
            }
        });
        jMenu6.add(cubo);

        Esfera.setText("Esfera");
        Esfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsferaActionPerformed(evt);
            }
        });
        jMenu6.add(Esfera);

        Piramide.setText("Piramide");
        Piramide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiramideActionPerformed(evt);
            }
        });
        jMenu6.add(Piramide);

        jMenu3.add(jMenu6);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu3.add(salir);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void circuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circuloActionPerformed
 int radio=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el Radio Del circulo"));
 String color=JOptionPane.showInputDialog("Ingrese el color Del circulo");
 circ =new Circulo(65,5,color);

 JOptionPane.showMessageDialog(cubo, " El Area del circulo "+circ.Cambiartamaño()+" Color:"+circ.getColor());

     // TODO add your handling code here:
    }//GEN-LAST:event_circuloActionPerformed

    private void EsferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsferaActionPerformed
    int radio=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el Radio De la Esfera"));
      String color=JOptionPane.showInputDialog("Ingrese el color Del circulo");
 
    es =new Esfera(radio,5,color);
     JOptionPane.showMessageDialog(cubo, " El Volumen del Esfera "+es.CalularVolumen()+"cm3\n"+" Color:"+es.getColor());

    // TODO add your handling code here:
    }//GEN-LAST:event_EsferaActionPerformed

    private void cuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuboActionPerformed
      String color=JOptionPane.showInputDialog("Ingrese el color Del cubo");
        Cub =new DatosCubo( 65,color);

        JOptionPane.showMessageDialog(null, Cub.CalularVolumen()+"cm3\n"+" Color:"+Cub.getColor());
        // TODO add your handling code here:
    }//GEN-LAST:event_cuboActionPerformed

    private void PiramideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiramideActionPerformed

        int altura=Integer.parseInt(JOptionPane.showInputDialog("Introduce el valor de la arista de la Piramide"));    
         String color=JOptionPane.showInputDialog("Ingrese el color De la piramide");

        Pira=new    Piramide (altura,5,color); // TODO add your handling code here:
        JOptionPane.showMessageDialog(cubo, " El Volumen del piramide "+Pira.CalcularVolumen()+"cm3\n"+" Color:"+Pira.getColor());  
        
    }//GEN-LAST:event_PiramideActionPerformed

    private void TrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrianguloActionPerformed
   int base=Integer.parseInt(JOptionPane.showInputDialog("Introduce el valor de la base"));   
  int altura=Integer.parseInt(JOptionPane.showInputDialog("Introduce el valor de la altura")); 
              String color=JOptionPane.showInputDialog("Ingrese el color De la piramide");

    tri=new Triangulo(base,altura,5,color);     
      JOptionPane.showMessageDialog(cubo, " El area del triangulo "+tri.Cambiartamaño()+"cm2\n"+" Color:"+tri.getColor());    
    // TODO add your handling code here:
    }//GEN-LAST:event_TrianguloActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void CuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadradoActionPerformed
 int lado=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el lado Del cuadrado"));
           String color=JOptionPane.showInputDialog("Ingrese el color Del cubo");
   
 cua =new DatosCuadrado(lado,54,color);
  cua.Cambiartamaño();

         JOptionPane.showMessageDialog(null,   "El area de cuadrado es:"+cua.Cambiartamaño()
+" \nColor:"+cua.getColor());

        // TODO add your handling code here:
    }//GEN-LAST:event_CuadradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuadrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cuadrado;
    private javax.swing.JMenuItem Esfera;
    private javax.swing.JMenuItem Piramide;
    private javax.swing.JMenuItem Triangulo;
    private javax.swing.JMenuItem circulo;
    private javax.swing.JMenuItem cubo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
